### ISSUE TITLE
缩放问题

### ISSUE THREAD

**Issue by johnren-code** [daidaibg/IofTV-Screen-Vue3#1]
大佬，你好，我把你的大屏集成在了我的一个网页上面，如下图所示：
![image](https://user-images.githubusercontent.com/76835772/236624092-b8bd6306-13cd-4173-bcb6-a4b12041de94.png)
但是，现在出现了一个问题，就是我每次缩小，放大网页的时候，这个大屏就会一直往下坠，下图所示：
![image](https://user-images.githubusercontent.com/76835772/236624166-1d33c961-85ca-41cf-a7f4-ec56d37626ba.png)
就是我不断地重复放大，缩小，他就会不停的往下坠，怎么解决这个问题呢，把大屏固定到一个位置，进行缩放与扩大
期待大佬的回复！谢谢！

**Comment by sincely** [comment]
vue3版本没有做屏幕分辨率适配,缩放问题没有处理好,不过界面挺好看的,author处理一下可以更完美!

**Comment by daidaibg** [comment]
> 大佬，你好，我把你的大屏放到了我的一个网页上面，如下图所示： 但是，现在出现了一个问题，就是我每次缩小小，放大网页的时候，这个大屏就会一直往下摔，下图说明： 就是我不断地重新放大，缩小，他就会不停的往下摔，怎么解决这个问题呢，把大屏固定到一个位置，进行缩小放与扩展等待大佬的 回复！谢谢！ ![图像](https://user-images.githubusercontent.com/76835772/236624092-b8bd6306-13cd-4173-bcb6-a4b12041de94.png) ![图像](https://user-images.githubusercontent.com/76835772/236624166-1d33c961-85ca-41cf-a7f4-ec56d37626ba.png)

你需要手动改下缩放适配那里，页面属于上下左右居中，你把上下居中那里换下就行了

**Comment by daidaibg** [comment]
https://github.com/daidaibg/IofTV-Screen-Vue3/issues/1#issue-1698610815

适配逻辑是上下左右居中，你把上下居中去掉一下就行了
