### ISSUE TITLE
Echarts图表不显示

### ISSUE THREAD

**Issue by hebaq** [daidaibg/IofTV-Screen-Vue3#2]
大佬，项目拉下来以后运行，这几个Echarts图表不显示
![image](https://github.com/daidaibg/IofTV-Screen-Vue3/assets/61929206/a7d525cf-9832-442b-973c-879782f025b3)

**Comment by daidaibg** [comment]
我这边目前不会出现这种问题，你的node 多少版本的

**Comment by hebaq** [comment]
已解决，升级了vue-echarts依赖
