### ISSUE TITLE
网络异常或者接口报错，返回的是Promise的resolve，最终页面接收到的是resolve的状态

### ISSUE THREAD

**Issue by desiredev** [daidaibg/IofTV-Screen-Vue3#3]
看图
![26159](https://github.com/daidaibg/IofTV-Screen-Vue3/assets/81085362/62c4c3a5-dc2c-4903-bb73-8e632ab44c95)

**Comment by daidaibg** [comment]
是的，你那样是正确标准做法，我们这里是为了少写一个.catch 错误信息也在resolve中处理了，处理数据那里全部是要么成功要么失败展示错误信息的
![image](https://github.com/daidaibg/IofTV-Screen-Vue3/assets/55817318/da60bcc5-9c32-4eee-9304-97d535ce4a69)

**Comment by daidaibg** [comment]
最新版本把请求写得更加规范，你可以拉下最新代码
